### ISSUE TITLE
Its needs to be fixed again for Android 10

### ISSUE THREAD

**Issue by amitcoolcampus** [YaDev/SamsungDualSimFix#2]
Hi YaDev,
![Screenshot_20200611-141029_Nova Launcher](https://user-images.githubusercontent.com/13386188/85052543-b8c05c80-b1b6-11ea-95bd-8f9e6d97914d.png)
I got the error again. Not sure if I am right, but I got this error when I cleared cache and dalvik memory and rebooted. I think error popped up before edxposed could load so I got the error and once it appeared there was no solution but to restart the phone. However I could notice behind the error, network was there for both the sims.

**Comment by YaDev** [comment]
I think this a normal problem since you cleared cache and dalvik memory. I had a issue like this before with a different module and just had to re-enable the module via EdXposed Manager.

**Comment by amitcoolcampus** [comment]
Right. This should be happening to other modules as well but we do not come to know. However in this case by default Android shows error without module so we get notified. Thanks.
